package com.example.myapplication;

import android.content.Context;
import android.content.Intent;
import android.support.annotation.NonNull;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import com.google.firebase.database.ChildEventListener;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.Query;
import com.google.firebase.database.ValueEventListener;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.UnsupportedEncodingException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Queue;
import java.util.Random;
import java.util.Scanner;
import java.util.Stack;
import java.util.Date;

public class MainActivity extends AppCompatActivity {


    Button button;
    Random random;
    DatabaseReference firebase;
    Gravador gravadorArquivos;
    @Override
    protected void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);
        firebase=FirebaseDatabase.getInstance().getReference();
        gravadorArquivos=new Gravador();
        gravadorArquivos.isDataCorreta(this);
        System.out.println("asdasdasd");
        //firebase.child("contQuestoes").setValue(0);
        gravarArquivo("NovasQuestoes.txt","false|Dólar, Peso e Iene|O dólar pertence aos EUA, o peso a Argentina e o iene ao Japão|false|Peso, Dólar e Iene|O peso pertence a Argentina, o dólar aos EUA e o iene ao Japão|false|Dólar, Iene e Peso|O dólar pertence aos EUA, o iene ao Japão e o peso a Argentina|false|Iene, Peso e Dólar|O iene pertence ao Japão, o peso a Argentina e o dólar aos EUA.|true|Peso, Iene e Dólar|O peso pertence a Argentina, o iene ao Japão e o dólar aos EUA.|Se não souber, utilize o método por eliminação.|fácil|Você sabia que cada país, possui uma moeda. Pedro pesquisou e descobriu as moedas da Argentina, Japão e dos Estados Unidos. Quais são suas respectivas moedas?|1|5|MOEDAS|\n" +
                "false|R$ 57,00|(2*20)+(1*10)+(1*5)=55-&gt;89-55=34|true|R$ 34,00|(2*20)+(1*10)+(1*5)=55-&gt;89-55=34|false|R$ 28,00|(2*20)+(1*10)+(1*5)=55-&gt;89-55=34|false|R$ 32,00|(2*20)+(1*10)+(1*5)=55-&gt;89-55=34|false|R$ 44,00|(2*20)+(1*10)+(1*5)=55-&gt;89-55=34|Somar o que ele já possui e subtrair do valor do skate.|fácil|Luiz está economizando para comprar um skate e ele já possui duas notas de vinte reais, uma de dez e uma de cinco. Se o skate que ele quer comprar custa R$89,00, quanto falta para poder comprá-lo?|1|10|GASTOS PESSOAIS|\n" +
                "false|Educação financeira|O ato de trocar seu produto por outro era chamada de escambo.|false|Moedas|O ato de trocar seu produto por outro era chamada de escambo.|true|Escambo|O ato de trocar seu produto por outro era chamada de escambo.|false|Cédulas|O ato de trocar seu produto por outro era chamada de escambo.|false|Finanças|O ato de trocar seu produto por outro era chamada de escambo.|Procure a palavra que mais se relaciona com o nome troca.|fácil|Você sabia que antes de existir o dinheiro as pessoas trocavam as coisas? Qual o nome dado a esse tipo de trocas?|1|15|MOEDAS|\n" +
                "false|Mariana e Liz|Mariana possui R$12 e Liz RS4|false|João e Liz|João possui R$10 e Liz RS4|false|Karina, Liz e João|Karina possui R$12, Liz RS4 e João R$10|true|Mariana e Karina|Mariana possui R$12 e Karina R$12|false|Karina, Mariana e Liz|Karina possui R$12, Mariana R$12 e Liz RS4|Primeiramente, calcular quanto cada um possui.|fácil|Mariana tem duas notas de cinco e uma de dois, João tem uma nota de dez, Liz tem duas notas de dois e Karina tem uma nota de dez e uma de dois. Quem são os que possuem a mesma quantia de dinheiro?|1|10|MOEDAS|\n" +
                "false|R$ 6,00|Lucas ganha R$4,00 e Gabriel R$10,00, então 4+10=14.|false|R$ 10,00|Lucas ganha R$4,00 e Gabriel R$10,00, então 4+10=14.|true|R$ 14,00|Lucas ganha R$4,00 e Gabriel R$10,00, então 4+10=14.|false|R$ 18,00|Lucas ganha R$4,00 e Gabriel R$10,00, então 4+10=14.|false|R$ 28,00|Lucas ganha R$4,00 e Gabriel R$10,00, então 4+10=14.|A cada ano de idade eles recebem um real.|fácil|Maria dá mesada a seus filhos de acordo com a idade: Lucas tem 4 anos e Gabriel tem 10. Lucas e Gabriel se juntaram e decidiram comprar o presente para seu pai. Qual é o valor que os dois possuíam?|1|10|GASTOS PESSOAIS|\n" +
                "false|R$ 18,00|60/2=30,00|false|R$ 24,00|60/2=30,00|true|R$ 30,00|60/2=30,00|false|R$ 42,00|60/2=30,00|false|R$ 60,00|60/2=30,00|1/2 equivalente a metade do valor.|fácil|Joana ganhou de presente de aniversário R$ 60,00 e quer comprar uma boneca. Para isto ela terá que guardar 1/2 do valor que ganhou. Qual o valor que Joana terá que guardar para comprar a boneca?|1|10|GASTOS PESSOAIS|\n" +
                "false|R$ 3,00|(2*1)+(2*2)=6 -> 10-6=4,00|true|R$ 4,00|(2*1)+(2*2)=6 -> 10-6=4,00|false|R$ 6,00|(2*1)+(2*2)=6 -> 10-6=4,00|false|R$ 7,00|(2*1)+(2*2)=6 -> 10-6=4,00|false|R$ 5,00|(2*1)+(2*2)=6 -> 10-6=4,00|Multiplique o valor do brinquedo pela quantidade que ele comprou.|fácil|Uma peteca custa R$2,00 e uma bola custa R$1,00. José ganhou R$10,00 para comprar os brinquedos. Quanto ele ainda tem de dinheiro se ele comprou duas bolas e duas petecas?|1|10|GASTOS PESSOAIS|\n" +
                "false|2 bonecas e sobraria R$20,00 de troco|2*25=50 -> 90-50=40|true|3 bonecas e sobraria R$15,00 de troco|3*25=75 -> 90-75= 15|false|4 bonecas e não sobraria troco|4*25=100 -> 90-100= -10|false|3 bonecas e sobraria R$25,00 de troco|3*25=75 -> 90-75=15|false|4 bonecas e sobraria R$5,00 de troco|4*25=100 -> 90-100= -10|A questão pede o máximo de bonecas que ela poderia comprar.|fácil|Em 2016 Amélia conseguiu poupar R$ 90,00, ao final do ano ela resolveu ir em uma loja de brinquedos e viu que uma boneca custava R$25,00. Com os R$90,00 quantas bonecas ela poderia comprar?|1|15|GASTOS PESSOAIS|\n" +
                "\n" +
                "false|R$ 130,00|Se cada um dará R$ 50,00, bastar fazer 50 * 4 = 200. Para saber o valor que falta, basta fazer 350 – 200 = 150. Logo 150 é a resposta certa!|true|R$ 150,00|Se cada um dará R$ 50,00, bastar fazer 50 * 4 = 200. Para saber o valor que falta, basta fazer 350 – 200 = 150. Logo 150 é a resposta certa!|false|R$ 125,00|Se cada um dará R$ 50,00, bastar fazer 50 * 4 = 200. Para saber o valor que falta, basta fazer 350 – 200 = 150. Logo 150 é a resposta certa!|false|R$ 180,00|Se cada um dará R$ 50,00, bastar fazer 50 * 4 = 200. Para saber o valor que falta, basta fazer 350 – 200 = 150. Logo 150 é a resposta certa!|false|R$ 145,00|Se cada um dará R$ 50,00, bastar fazer 50 * 4 = 200. Para saber o valor que falta, basta fazer 350 – 200 = 150. Logo 150 é a resposta certa!|Deve-se usar operações básicas da matemática para saber o valor que falta para comprar|fácil|A família de Lucas lhe dará uma bicicleta que custa R$ 350,00. O pai, a mãe e os dois irmãos irão dar R$ 50,00 cada. Quanto falta para comprar a bicicleta?|2|10|GASTOS PESSOAIS|\n" +
                "false|Gastos iguais a R$ 130,00 e troco R$ 20,00|O somatório de todas as peças compradas dá o resultado de R$ 135,00 e o troco de R$ 15,00|false|Gastos iguais a R$ 150,00 e troco R$ 0|O somatório de todas as peças compradas dá o resultado de R$ 135,00 e o troco de R$ 15,00|true|Gastos iguais a R$ 135,00 e troco R$ 15,00|O somatório de todas as peças compradas dá o resultado de R$ 135,00 e o troco de R$ 15,00|false|Gastos iguais a R$ 100,00 e troco R$ 50,00|O somatório de todas as peças compradas dá o resultado de R$ 135,00 e o troco de R$ 15,00|false|Gastos iguais a R$ 90,00 e troco R$ 60,00|O somatório de todas as peças compradas dá o resultado de R$ 135,00 e o troco de R$ 15,00|O valor do troco será o valor gasto menos o que se tem disponível|fácil|Henrique possui R$ 150,00. Qual o total gasto e valor do troco se ele comprar: 1 calça (R$ 80 cada); 2 blusa (R$ 20 cada); 1 meia (R$ 15,00 cada)?|2|15|GASTOS PESSOAIS|\n" +
                "false|4 vestidos; 2 blusas e 3 saias|O somatório dessa opção da R$ 550|false|3 vestidos; 4 blusas e 2 saias|O somatório dessa opção da R$ 530|true|4 vestidos; 2 blusas e 4 saias|O somatório dessa opção da exatamente R$ 600!|false|3 vestidos; 4 blusas e 3 saias|O somatório dessa opção da R$ 570|false|2 vestidos; 3 blusas e 4 saias|O somatório dessa opção da R$ 490|Se deve comparar o valor das vendas com o valor preciso|fácil|Julia precisa de R$ 600 com venda de roupas num brechó. Os Valores das peças são: Vestidos R$80,00; Blusas R$50,00; Saias R$45,00. Quantas peças precisam ser vendidas para alcançar o valor?|2|15|GASTOS PESSOAIS|\n" +
                "false|2 reais - peixe azul; 5 reais - arara; 10 reais - papagaio|A sequencia correta é: tartaruga de pente; garça branca; arara vermelha|true|2 reais -tartaruga de pente; 5 reais - garça branca; 10 reais - arara vermelha|A sequencia correta é exatamente: tartaruga de pente; garça branca; arara vermelha!|false|2 reais - tartaruga; 5 reais - passarinho; 10 reais - garça|A sequencia correta é exatamente: tartaruga de pente; garça branca; arara vermelha!|false|2 reais - tatu; 5 reais - ganso; 10 reais -passarinho|A sequencia correta é: tartaruga de pente; garça branca; arara vermelha|false|2 reais - tartaruga de pente; 5 reais - garça branca; 10 reais -papagaio,|A sequencia correta é: tartaruga de pente; garça branca; arara vermelha|O tatu não está em nenhuma cédula brasileira|fácil|Assinale a alternativa correta com relação às cédulas brasileiras e aos animais nas notas:|2|5|MOEDAS|\n" +
                "false|1 semana|Em 1 semana ele teria apenas 25 reais|false|2 semanas|Em 2 semanas ele teria apenas 50 reais|false|3 semanas|Em 3 semanas ele teria apenas 75 reais|true|4 semanas|Em 4 semanas ele teria exatamente 100 reais!|false|5 semanas|Em 5 semanas ele teria 125 reais, já ultrapassa o valor necessário|Usa-se a operação de multiplicação|fácil|Marcelo quer comprar uma bicicleta que custa R$ 100,00. Sabendo que ele ganha R$ 25,00 por semana, quantas semanas serão necessárias para realizar a compra?|2|5|GASTOS PESSOAIS|\n" +
                "false|R$ 60,00 e 2 meses|Basta subtrair o valor que já se tem pelo valor da compra, resultando em 90 e posteriormente, dividir pelo valor da mesada, igual a 3.|false|R$ 90,00 e 2 meses|Basta subtrair o valor que já se tem pelo valor da compra, resultando em 90 e posteriormente, dividir pelo valor da mesada, igual a 3.|false|R$ 30,00 e 1 meses|Basta subtrair o valor que já se tem pelo valor da compra, resultando em 90 e posteriormente, dividir pelo valor da mesada, igual a 3.|true|R$ 90,00 e 3 meses|Basta subtrair o valor que já se tem pelo valor da compra, resultando em 90 e posteriormente, dividir pelo valor da mesada, igual a 3.|false|R$ 60,00 e 3 meses|Basta subtrair o valor que já se tem pelo valor da compra, resultando em 90 e posteriormente, dividir pelo valor da mesada, igual a 3.|É possível resolver utilizando operações básicas da matemática|fácil|Ana ganha mesada de R$ 30,00 e quer comprar uma câmera de R$ 180,00. Ela já possui R$ 90,00 reais. Quanto falta de valor e de meses necessários para fazer a compra?|2|10|GASTOS PESSOAIS|\n" +
                "false|R$ 35,00|20 + 10 + 5 = 55 reais. Para 80 reais ainda falta 25 reais.|false|R$ 27,00|20 + 10 + 5 = 55 reais. Para 80 reais ainda falta 25 reais.|true|R$ 25,00|20 + 10 + 5 = 55 reais. Para 80 reais ainda falta exatamente 25 reais!|false|R$ 30,00|20 + 10 + 5 = 55 reais. Para 80 reais ainda falta 25 reais.|false|R$ 37,00|20 + 10 + 5 = 55 reais. Para 80 reais ainda falta 25 reais.|Deve-se somar os valores das cédulas|fácil|João quer comprar um livro de R$ 80,00. Ele possui duas notas de R$ 20,00, uma de R$ 10,00 e uma e R$ 5,00. Quanto falta para comprar o livro?|2|5|GASTOS PESSOAIS|\n" +
                "false|1 ano|Basta subtrair 300 e 900 = 600. Como ela ganha 100 mensalmente, ainda faltam 6 meses.|true|6 meses|Basta subtrair 300 e 900 = 600. Como ela ganha 100 mensalmente, ainda faltam 6 meses!|false|8 meses|Basta subtrair 300 e 900 = 600. Como ela ganha 100 mensalmente, ainda faltam 6 meses.|false|3 meses|Basta subtrair 300 e 900 = 600. Como ela ganha 100 mensalmente, ainda faltam 6 meses.|false|5 meses|Basta subtrair 300 e 900 = 600. Como ela ganha 100 mensalmente, ainda faltam 6 meses.|É possível resolver utilizando operações básicas da matemática|fácil|Paula quer comprar uma TV de R$ 900,00. Sabe-se que ela recebe mesada de R$ 100,00 e já possui R$ 300,000. Quanto tempo será necessário para comprar a TV?|2|10|GASTOS PESSOAIS|\n" +
                "false|R$ 15,78|Se meia dúzia é igual a 7,89, uma dúzia é igual a 7,89 *2 = 15,78. Logo, 3 dúzias será 15,78 * 3 = 47,34.|false|R$ 23,67|Se meia dúzia é igual a 7,89, uma dúzia é igual a 7,89 *2 = 15,78. Logo, 3 dúzias será 15,78 * 3 = 47,34.|false|R$ 25,71|Se meia dúzia é igual a 7,89, uma dúzia é igual a 7,89 *2 = 15,78. Logo, 3 dúzias será 15,78 * 3 = 47,34.|true|R$ 47,34|Se meia dúzia é igual a 7,89, uma dúzia é igual a 7,89 *2 = 15,78. Logo, 3 dúzias será 15,78 * 3 = 47,34!|false|R$ 63,12|Se meia dúzia é igual a 7,89, uma dúzia é igual a 7,89 *2 = 15,78. Logo, 3 dúzias será 15,78 * 3 = 47,34.|Uma dúzia é igual a 12|fácil|Em um supermercado conhecido da cidade de João Pessoa, meia dúzia de ovos custa R$7,89 reais. Quanto custam 3 dúzias?|2|15|OPERAÇÕES|\n" +
                "false|R$ 24,50|Quando os itens são somados resulta num valor de 12,20. O troco será 18,40- 12,20= 6,25!|false|R$ 5,50|Quando os itens são somados resulta num valor de 12,20. O troco será 18,40- 12,20= 6,25!|false|R$ 6,55|Quando os itens são somados resulta num valor de 12,20. O troco será 18,40- 12,20= 6,25!|false|R$ 5,25|Quando os itens são somados resulta num valor de 12,20. O troco será 18,40- 12,20= 6,25!|true|R$ 6,25|Quando os itens são somados resulta num valor de 12,20. O troco será 18,40- 12,20= 6,25!|O troco será a sobra após os itens comprados|fácil|João foi à padaria com R$ 18,40. Ele comprou os seguintes itens: caixa de leite R$ 3,50; 10 pães R$ 5,90; 5 ovos R$ 2,75. Quanto ele teve de troco?|2|15|GASTOS PESSOAIS|\n" +
                "false|R$ 25,00 reais|Basta multiplicar o valor unitário de cada fruta e somar (3*15) + (6*5) = 45 reais.|false|R$ 20,00 reais|Basta multiplicar o valor unitário de cada fruta e somar (3*15) + (6*5) = 45 reais.|false|R$ 15,00 reais|Basta multiplicar o valor unitário de cada fruta e somar (3*15) + (6*5) = 45 reais.|false|R$ 30,00 reais|Basta multiplicar o valor unitário de cada fruta e somar (3*15) + (6*5) = 45 reais.|true|R$ 45,00 reais|Basta multiplicar o valor unitário de cada fruta e somar (3*15) + (6*5) = 45 reais.|Deve-se usar operações básicas para resolver|fácil|Mônica fez compra de frutas nos seguintes valores: 3 melões por R$ 5,00 reais cada e 6 maçãs por R$ 5,00 reais. Qual valor da lista de gastos da Mônica?|2|15|GASTOS PESSOAIS|\n" +
                "true|R$ 4,00; R$ 11,00; R$2,00;|É preciso subtrair o valor pago do valor do produto: 10-6 = 4; 20-9 = 11; 5-3 = 2.|false|R$ 6,00; R$ 11,00 R$ 3,00|É preciso subtrair o valor pago do valor do produto: 10-6 = 4; 20-9 = 11; 5-3 = 2.|false|R$ 10,00; R$10,00; R$ 4,00|É preciso subtrair o valor pago do valor do produto: 10-6 = 4; 20-9 = 11; 5-3 = 2.|false|R$ 8,00; R$9,00; R$ 2,00|É preciso subtrair o valor pago do valor do produto: 10-6 = 4; 20-9 = 11; 5-3 = 2.|false|R$ 9,00; R$10,00|É preciso subtrair o valor pago do valor do produto: 10-6 = 4; 20-9 = 11; 5-3 = 2.|Basta utilizar de operações matemáticas|fácil|Indique o valor o troco das respectivas compras: valor 6,00 pagamento 10,00; valor 9,00 pagamento 20,00; valor 3,00 pagamento 5,00.|2|5|GASTOS PESSOAIS|\n" +
                "true|Todas as receitas, despesas e gastos|Correta. É a partir do registro de todas as receitas, despesas e gastos do período em questão que se obtém o controle sobre suas finanças|false|Gastos e despesas|Errada. Devem estar presentes, porém a alternativa está incompleta.|false|Receitas e prejuízos|Errada. Faltaram outros elementos como gastos, e prejuízo pode ser ou não o resultado do período em questão.|false|Despesas e lucros.|Errada. Despesa deve estar inclusa no orçamento, porém lucro pode ser ou não o resultado do período em análise|false|Prejuízo e lucro|Errada. Pois a questão correta é. Receitas, despesas e gastos.|O orçamento possibilita que flua mais facilmente as finanças pessoais e familiar|fácil|Ter controle de suas finanças é muito importante para que se tenha conhecimento e controle financeiro. No orçamento pessoal os componentes básicos são:|2|5|CONCEITOS DE EDUCAÇÃO FINANCEIRA*ORÇAMENTO PESSOA E FAMILIAR|\n" +
                "false|A mais cara, já que a marca é mais conhecida.|Errado. Já que a marca não significa qualidade|true|A mais barata, pois possui a mesma utilidade|Correta, já que terá a mesma utilidade|false|A mais cara, já que sua mãe deu os 5 reais|Errado. Sua mãe lhe pediu para comprar a caneta barata|false|A mais cara, já que terá a mesma utilidade|Errada. A barata compensa mais que a cara|false|Nenhuma das alternativas|Errado. A alternativa certa é a letra “B”|Deve-se levar em consideração o que realmente é necessário na hora da compra|fácil|Graça tem duas opções de compra pra uma caneta: uma por R$ 2,00 com aparência “comum” e outra por 5 reais, mudando apenas a marca. Qual ela deverá escolher?|2|5|CONCEITOS DE EDUCAÇÃO FINANCEIRA|\n" +
                "\n" +
                "true|É um acordo informal entre fornecedor e consumidor.|Certa, pois os fornecedores e consumidores não precisam de um acordo formal para obtenção do cheque pré-datado.|false|Meio que possibilita o pagamento à vista ou parcelado da compra de produtos ou serviços.|Errado, isto se refere a outro tipo de pagamento.|false|Permite que seu dinheiro seja debitado em conta corrente no ato da compra.|Errado, isto se refere a outro tipo de pagamento.|false|Limite de crédito que um banco oferece além do seu saldo.|Errado, isto se refere a outro tipo de pagamento.|false|É o desembolso em espécie.|Errado, isto se refere a outro tipo de pagamento.|É uma forma de acordo.|fácil|Assinale a alternativa que melhor se adequa ao Cheque pré-datado:|3|5|FORMAS DE PAGAMENTO|\n" +
                "false|Cheque pré-datado|Errado, pois fala de outro tipo de pagamento.|true|Cheque Especial|Certo, pois condiz com o que a questão pede.|false|Cartão de Crédito|Errado, pois fala de outro tipo de pagamento.|false|Cartão de Débito|Errado, pois fala de outro tipo de pagamento.|false|Pagamento à vista|Errado, pois fala de outro tipo de pagamento.|É um tipo de cheque.|fácil|Limite de crédito que um banco oferece além do seu saldo. A que se refere a parte destacada do texto?|3|5|FORMA DE PAGAMENTO|\n" +
                "false|É um acordo informal entre fornecedor e consumidor.|Errado, pois fala de outro tipo de pagamento.|false|Meio que possibilita o pagamento à vista ou parcelado da compra de produtos ou serviços.|Errado, pois fala de outro tipo de pagamento.|true|Permite que seu dinheiro seja debitado em conta corrente no ato da compra.|Certo, pois é a definição correta.|false|Limite de crédito que um banco oferece além do seu saldo.|Errado, pois fala de outro tipo de pagamento.|false|Desembolso em espécie.|Errado, pois fala de outro tipo de pagamento.|Só podemos comprar algo no débito quando possuímos dinheiro em nossa conta.|fácil|Assinale a opção que descreve melhor o Cartão de Débito:|3|5|PAGAMENTO|\n" +
                "false|Barão do Rio|Errado, pois quem está no anverso desta moeda é Deodoro da Fonseca.|true|Deodoro da Fonseca|Certo, pois ele é quem está no anverso desta moeda.|false|Dom Pedro I|Errado, pois quem está no anverso desta moeda é Deodoro da Fonseca.|false|Pedro Álvares Cabral|Errado, pois quem está no anverso desta moeda é Deodoro da Fonseca.|false|Tiradentes|Errado, pois quem está no anverso desta moeda é Deodoro da Fonseca.|Foi um militar e político brasileiro, primeiro presidente do Brasil e uma das figuras centrais da Proclamação da República no país.|fácil|Qual figura histórica se encontra no anverso da moeda de 25 centavos acobreada?|3|10|MOEDAS BRASILEIRAS|\n" +
                "true|Comprar por impulso.|Correto, pois o supérfluo vem justamente da impulsividade de comprar coisas desnecessárias.|false|Antes de fazer compras, identificar suas necessidades.|desnecessárias.|false|Dar prioridade às despesas necessárias.|Errado, pois o supérfluo vem da impulsividade de comprar coisas desnecessárias.|false|Conseguir guardar parte da mesada para investir.|Errado, pois o supérfluo vem da impulsividade de comprar coisas desnecessárias.|false|Se é algo que não for usar no curto prazo, não comprar.|Errado, pois o supérfluo vem da impulsividade de comprar coisas desnecessárias.|Pense no que é importante e essencial para a sua vida. Esta é a alternativa errada.|fácil|Na Educação Financeira um dos conceitos fundamentais e muito usado quando está se aprendendo sobre o tema, é o Supérfluo (algo desnecessário, dispensável). Qual alternativa representa algo Supérfluo?|3|5|NECESSIDADE X DESEJO|\n" +
                "false|7 semanas|Errado, pois 1,60*5 = 8; 8*5 = 40; 40+90 = 130.|false|4 semanas|Errado, pois 1,60*5 = 8; 8*5 = 40; 40+90 = 130.|false|6 semanas|Errado, pois 1,60*5 = 8; 8*5 = 40; 40+90 = 130.|false|3 semanas|Errado, pois 1,60*5 = 8; 8*5 = 40; 40+90 = 130.|true|5 semanas|Certa, pois 1,60*5 = 8; 8*5 = 40; 40+90 = 130.|Ele precisa juntas 40 reais e consegue poupar 8 por semana.|fácil|Pedro quer um jogo de R$ 130,00, mas só tem R$ 90,00. Então decidiu ir a pé para a escola para poupar uma passagem que custa R$ 1,60. Em quantas semanas ele conseguirá o resto do dinheiro?|3|10|DESEJO X NECESSIDADE|\n" +
                "false|1 ano e 1 mês|Errado, pois 24000 – 7000 = 17000; 17000/1000 = 17; 17 = 12 + 5.|false|1 ano e 2 meses|Errado, pois 24000 – 7000 = 17000; 17000/1000 = 17; 17 = 12 + 5.|false|1 ano e 3 meses|Errado, pois 24000 – 7000 = 17000; 17000/1000 = 17; 17 = 12 + 5.|false|1 ano e 4 meses|Errado, pois 24000 – 7000 = 17000; 17000/1000 = 17; 17 = 12 + 5.|true|1 ano e 5 meses|Certo, pois 24000 – 7000 = 17000; 17000/1000 = 17; 17 = 12 + 5.|Ele precisa de 17000 reais, pois já possui 7000.|fácil|Marcos ganha 2000 mil reais por mês e usa mil para pagar as despesas. Há sete meses, ele guarda o resto para comprar à vista um carro de R$ 24000,00. Falta quanto tempo para ele realizar seu sonho?|3|10|DESEJO*POUPANÇA|\n" +
                "false|R$ 100,00|Errado, pois 30/5 = 6; 6*30 = 180; 180 – 30 = 150.|false|R$ 180,00|Errado, pois 30/5 = 6; 6*30 = 180; 180 – 30 = 150.|true|R$ 150,00|Certo, pois 30/5 = 6; 6*30 = 180; 180 – 30 = 150.|false|R$ 190,00|Errado, pois 30/5 = 6; 6*30 = 180; 180 – 30 = 150.|false|R$ 170,00|Errado, pois 30/5 = 6; 6*30 = 180; 180 – 30 = 150.|Tire o custo do valor final|fácil|Bia quer presentear sua mãe e para isso vende beijinho. Seu avô lhe dá R$ 30,00 para comprar latas de beijinho que custam R$ 5,00 e rendem 30 beijinhos que valem R$ 1,00 cada. Quanto ela lucrará?|3|15|EMPREENDEDORISMO*CUSTO|\n" +
                "false|Ato de gastar sem pensar no futuro.|Errado, é exatamente o contrário.|false|Ação de não pensar antes de gastar.|Errado, é o oposto.|true|Um trabalho onde se estabelece objetivos, prazos e os meios para se realizar.|Certo, são necessárias metas para atingir seus objetivos.|false|Comprar tudo que vemos pela frente, sem pensar.|Errado, isso levaria o indivíduo à falência e endividamento.|false|É um desperdício de dinheiro e de energia e o dinheiro pode fazer falta no fim do mês.|Errado, desperdício é o que se tem quando não há planejamento financeiro.|Planejamento = Organização = Sem surpresas que você não pode superar.|fácil|O que é um Planejamento Financeiro? Marque a alternativa correta:|3|10|PLANEJAMENTO FINANCEIRO|\n" +
                "false|Álcool, pois será necessário 27L dele e gastaria 30 litros com gasolina.|Errado, pois com álcool ele gastaria 75 reais e com gasolina gastaria 70.|true|Gasolina, pois este terá uma economia de R$ 5,00 se comparado ao etanol.|Certo, pois com álcool ele gastaria 75 reais e com gasolina gastaria 70.|false|Álcool, pois gastará R$ 70,00 com este e gastaria R$ 75,00 com etanol.|Errado, pois com álcool ele gastaria 75 reais e com gasolina gastaria 70.|false|Gasolina, pois gastará R$ 80,00 com este e gastaria R$ 100,00 com etanol.|Errado, pois com álcool ele gastaria 75 reais e com gasolina gastaria 70.|false|Álcool, pois economizaria de 10 litros se comparado com gasolina.|Errado, pois com álcool ele gastaria 75 reais e com gasolina gastaria 70.|Utilize regra de 3 nesta aqui.|fácil|Paulo fará uma viagem de 200 km com seu carro bicombustível que faz 8km/L com etanol (R$ 3,00) e 10km/L com gasolina (R$ 3,50). Com qual combustível Paulo gastará menos?|3|15|ECONOMIA|\n" +
                "false|R$ 110,00 e R$ 70,00|Errado, pois 30/5 = 6; 6*23 = 138; 180 – 138 = 42.|true|R$ 138,00 e R$ 42,00|Certo, pois 30/5 = 6; 6*23 = 138; 180 – 138 = 42.|false|R$ 135,00 e R$ 45,00|Errado, pois 30/5 = 6; 6*23 = 138; 180 – 138 = 42.|false|R$ 120,00 e R$ 60,00|Errado, pois 30/5 = 6; 6*23 = 138; 180 – 138 = 42.|false|R$ 142,00 e R$ 38,00|Errado, pois 30/5 = 6; 6*23 = 138; 180 – 138 = 42.|Divida a quantidade de dias do mês pelo intervalo de dias de salão.|fácil|Em Julho, Isabela ia ao salão a cada 5 dias e gastava R$ 23,00 em cada. Sabendo que ela tem R$ 180,00, quanto ela gastou e sobrou no fim do mês, respectivamente?|3|10|CONSUMISMO|\n" +
                "false|Qualquer quantidade de moeda para ser aplicada ou emprestada.|Errado, este é o conceito de capital.|false|Valor final do capital aplicado|Errado, este é o conceito de montante.|false|Coeficiente percentual em função do qual o juro é calculado|Errado, este é o conceito de taxa.|true|Compensação financeira ou rendimentos conseguidos por capital aplicado.|Certo, este é o conceito de juros.|false|Prazo compreendido entre o início e o final da operação.|Errado, este é o conceito de tempo.|Todos fazem parte de uma fórmula de juros simples.|fácil|Nas alternativas a baixo marque o conceito de Juros.|3|15|JUROS|\n" +
                "false|R$ 784,50|Errado, pois 365*0,50 = 182,50; 365*2 = 730; 730+ 182,5 = 912,50.|false|R$ 850,00|Errado, pois 365*0,50 = 182,50; 365*2 = 730; 730+ 182,5 = 912,50.|false|R$ 925,50|Errado, pois 365*0,50 = 182,50; 365*2 = 730; 730+ 182,5 = 912,50.|true|R$ 912,50|Certo, pois 365*0,50 = 182,50; 365*2 = 730; 730+ 182,5 = 912,50.|false|R$ 875,00|Errado, pois 365*0,50 = 182,50; 365*2 = 730; 730+ 182,5 = 912,50.|Multiplique a quantidade de dias pelo valor das moedas colocadas em cada ano.|fácil|Pedro tem um cofre há três anos e coloca uma moeda nele todos os dias. No primeiro ano só colocou moedas de R$ 0,50 e nos outros dois, apenas de R$ 1,00. Quanto ele tem agora?|3|5|VALOR DA MOEDA NO TEMPO|\n" +
                "\n" +
                "false|Poupança|Errado. Esta é uma reserva constituída pelas pessoas.|false|Debênture|Errado. Este título é emitido pelas Empresas.|true|Certificado de Depósito Bancário (CDB)|Correto. Este é o título.|false|Ações|Errado. As ações são pequenas partes do capital das empresas.|false|Título Público|Errado. Este é um título emitido pelo Poder Público.|Observe quem está em busca de capitalização.|fácil|Título que os bancos emitem para se capitalizar, ou seja, conseguir dinheiro para financiar suas atividades de crédito. Tal conceito se refere a:|4|10|SISTEMA FINANCEIRO|\n" +
                "false|Precaver-se contra despesas inesperadas não é um motivo para poupar.|Este pode ser um motivo para poupar.|true|O hábito de poupar pode contribuir para organizar as finanças pessoais.|A poupança é um importante mecanismo das finanças pessoais.|false|Poupar não é uma boa opção, pois deixamos de consumir no presente.|Poupar é uma boa opção para manter nosso poder de consumo futuro.|false|Poupar não é bom, pois você perde dinheiro.|Você não perde dinheiro, apenas guarda-o.|false|Possuir uma poupança não facilita a realização de sonhos pessoais.|Facilita a realização de sonhos que necessitem de um montante maior.|A poupança gera benefícios futuros.|fácil|Poupança é a diferença positiva entre as receitas e as despesas, ou seja, entre tudo que ganhamos e tudo que gastamos. Podemos afirmar que é uma razão para poupar:|4|5|POUPANÇA|\n" +
                "true|Meio que possibilita o pagamento à vista ou parcelado da compra de produtos.|Correto.|false|Permite que seu dinheiro seja debitado em conta corrente no ato da compra.|Errado. Esta é uma característica do cartão de débito.|false|É o limite de crédito que um banco oferece além do seu saldo.|Errado. Esta é uma característica do cheque especial.|false|É um acordo informal entre fornecedor e consumidor.|Errado. Esta é uma característica do cheque pré-datado.|false|Cédulas de papel, considerada o meio de pagamento mais tradicional.|Errado. Esta é uma característica das cédulas de dinheiro.|Cartão de crédito é um auxílio para pagamentos futuros.|fácil|Sobre cartão de crédito, marque a alternativa correta:|4|5|MEIOS DE PAGAMENTO*CARTÃO DE CRÉDITO|\n" +
                "false|Meio que possibilita o pagamento à vista ou parcelado da compra de produtos.|Errado. Esta é uma característica do cartão de crédito.|true|Permite que seu dinheiro seja debitado em conta corrente no ato da compra.|Correto.|false|É o limite de crédito que um banco oferece além do seu saldo.|Errado. Esta é uma característica do cheque especial.|false|É um acordo informal entre fornecedor e consumidor.|Errado. Esta é uma característica do cheque pré-datado.|false|Cédulas de papel, considerada o meio de pagamento mais tradicional.|Errado. Esta é uma característica das cédulas de dinheiro.|Recorde qual fato está ligado à emissão do cartão de débito.|fácil|Sobre cartão de débito, marque a alternativa correta:|4|5|MEIOS DE PAGAMENTO*CARTÃO DE DÉBITO|\n" +
                "false|É importante refletir antes de tomar crédito.|Errado. Este é uma afirmativa que retrata um bom comportamento.|false|O cartão de crédito pode ser uma alternativa para realizar compras.|Errado. Este é uma afirmativa que retrata a realidade.|false|Devemos estar cientes de que, ao tomar crédito, limitamos o consumo futuro.|Errado. Este é uma afirmativa que retrata a realidade.|true|Devo adquirir um produto mesmo que tenha dificuldade para pagar.|Correto. Esta afirmativa retrata o uso inadequado do crédito.|false|O crédito é uma opção para quando não temos o montante no momento da compra.|Errado. Este é uma afirmativa que retrata a realidade.|O uso inadequado do crédito causará dificuldades em nossas vidas.|médio|O uso inadequado do crédito pode levar ao endividamento excessivo e comprometer toda a sua vida financeira. Marque a alternativa que retrata o uso inadequado do crédito.|4|5|CRÉDITO*EMPRÉSTIMOS|\n" +
                "true|R$29.600,00|Correto. J = 20.000 x 0,02 x 24 = 9.600. M = 20.000 + 9.600 = 29.600,00|false|R$30.000,00|Errado. J = 20.000 x 0,02 x 24 = 9.600. M = 20.000 + 9.600 = 29.600,00. 30.000 != 29.600.|false|R$31.300,00|Errado. J = 20.000 x 0,02 x 24 = 9.600. M = 20.000 + 9.600 = 29.600,00. 30.000 != 29.600.|false|R$32.600,00|Errado. J = 20.000 x 0,02 x 24 = 9.600. M = 20.000 + 9.600 = 29.600,00. 30.000 != 29.600.|false|R$33.300,00|Errado. J = 20.000 x 0,02 x 24 = 9.600. M = 20.000 + 9.600 = 29.600,00. 30.000 != 29.600.|Atente-se para utilizar a mesma unidade de medida com a taxa e o tempo.|médio|Rafael vai ao banco e solicita um empréstimo de R$20.000,00, a uma taxa de 2% a.m de juros simples, sendo pago após 2 anos. Qual o valor total pago ao final destes dois anos:|4|5|MATEMÁTICA FINANCEIRA*JUROS SIMPLES|\n" +
                "false|R$ 210,60|Errado. J = 1.800 x 0,0325 x 3 = 175,50. 210,60 != 175,50.|false|R$ 7.020,00|Errado. J = 1.800 x 0,0325 x 3 = 175,50. 210,60 != 175,50.|false|R$ 577,80|Errado. J = 1.800 x 0,0325 x 3 = 175,50. 210,60 != 175,50.|true|R$ 175,50|Correto. J = 1.800 x 0,0325 x 3 = 175,50. 210,60 != 175,50.|false|R$ 2.106,00|Errado. J = 1.800 x 0,0325 x 3 = 175,50. 210,60 != 175,50.|Que tal transformar a taxa em mensal?|fácil|Ana realizou uma aplicação no valor de R$ 1.800,00, por um período de 3 meses, com taxa de remuneração de 39% ao ano de juros simples. Quanto ela receberá de juros no resgate:|4|10|MATEMÁTICA FINANCEIRA*JUROS SIMPLES|\n" +
                "false|R$ 1.000,00|Errado. 34.000 – 26.000 = 8.000 x 15% = 1.200,00. 1.000 != 1.200.|true|R$ 1.200,00|Errado. 34.000 – 26.000 = 8.000 x 15% = 1.200,00.|false|R$ 1.600,00|Errado. 34.000 – 26.000 = 8.000 x 15% = 1.200,00. 1.000 != 1.200.|false|R$ 1.800,00|Errado. 34.000 – 26.000 = 8.000 x 15% = 1.200,00. 1.000 != 1.200.|false|R$ 2.000,00|Errado. 34.000 – 26.000 = 8.000 x 15% = 1.200,00. 1.000 != 1.200.|O pagamento para a Receita Federal é de 15% do lucro obtido com a venda das ações.|fácil|Um contribuinte que vende por R$ 34.000,00 um lote de ações que custou R$ 26.000,00 terá que pagar de Imposto de Renda à Receita Federal o valor de:|4|15|INVESTIMENTOS*TRIBUTOS|\n" +
                "false|Ato de gastar sem pensar no futuro.|Errado. Esta atitude não corresponde ao conceito de Planejamento Financeiro.|false|Ação de não pensar antes de gastar.|Errado. Esta atitude não corresponde ao conceito de Planejamento Financeiro.|true|Um trabalho no qual se estabelece objetivos, prazos e os meios para se realizar.|Correto. Essa afirmativa está enquadrada dentro do conceito de Planejamento Financeiro.|false|Comprar tudo que vemos pela frente, sem pensar.|Errado. Esta atitude não corresponde ao conceito de Planejamento Financeiro.|false|É um desperdício de dinheiro e de energia.|Errado. Esta atitude não corresponde ao conceito de Planejamento Financeiro.|O Planejamento Financeiro é algo que contribui para a nossa realidade.|fácil|O que é um Planejamento Financeiro?|4|5|PLANEJAMENTO FINANCEIRO|\n" +
                "false|Juros é o valor que pagamos por usar um dinheiro que não é nosso.|Errado. Esta frase retrata adequadamente o conceito de juros.|true|Montante é o valor que foi emprestado.|Correto. Esta frase retrata inadequadamente o conceito de montante.|false|A taxa de juros é o percentual utilizado para o cálculo dos juros.|Errado. Esta frase retrata adequadamente o conceito da taxa de juros.|false|O tempo é o período que o empréstimo dura.|Errado. Esta frase retrata adequadamente o conceito de tempo.|false|O capital é o valor do montante menos os juros.|Errado. Esta frase retrata adequadamente o conceito de capital.|Atente-se na diferença dos conceitos de capital e montante.|fácil|Com base nos seus conhecimentos sobre matemática financeira, marque a alternativa incorreta:|4|10|MATEMÁTICA FINANCEIRA*CAPITAL*JUROS|\n" +
                "\n" +
                "false|Aplicar em caderneta de poupança com rendimento de 0,75%, isenta de IR.|O rendimento líquido será de R$ 7,50 reais.|false|Aplicar em renda fixa com rendimento de 0,98% e IR de 22,5% (até 180 dias).|O rendimento da aplicação será de R$ 9,80 reais que subtraído 22,5% de IR (R$ 2,20 reais) ficará um rendimento líquido de R$ 7,60 reais.|false|Aplicar no tesouro direto com rendimento de 0,95% e IR de 17,5%(+360 dias).|O rendimento da aplicação será de R$ 9,50 reais que subtraído 17,5% de IR (R$ 1,70) ficará um rendimento líquido de R$ 7,80|true|Aplicar em renda variável com expectativa de 1,1% e IR de 25%.|O rendimento da aplicação será de R$ 11 reais que subtraído 25% de IR (R$ 2,70) ficará um rendimento líquido de R$ 8,30.|false|Comprar o carro com entrada de R$ 1.000,00 + 23 parcelas com juros de 2,5% am.|Essa não é a melhor opção porque ele pagará juros.|O imposto de renda (IR) incide sobre o lucro, não sobre o valor total da aplicação.|fácil|João aos 18 anos recebeu do seu pai mil reais e caso fizesse a melhor aplicação receberia 23 parcelas do mesmo valor para comprar seu carro. Dessa forma, qual a melhor alternativa para o João?|5|15|INVESTIMENTOS*VALOR DO DINHEIRO NO TEMPO|\n" +
                "false|R$ 55,00|R$250*0.02(2%) = R$5,00 de juros ao dia. 10 dias * R$5,00 = R$50,00|false|R$ 300,00|R$250*0.02(2%) = R$5,00 de juros ao dia. 10 dias * R$5,00 = R$50,00|false|R$ 5.250,00|R$250*0.02(2%) = R$5,00 de juros ao dia. 10 dias * R$5,00 = R$50,00|true|R$ 50,00|R$250*0.02(2%) = R$5,00 de juros ao dia. 10 dias * R$5,00 = R$50,00|false|R$ 305,00|R$250*0.02(2%) = R$5,00 de juros ao dia. 10 dias * R$5,00 = R$50,00|Multiplique o valor do boleto por 0.02|fácil|Fracinaldo pagou um de R$250,00 boleto 10 dias após o vencimento. Ao ler as observações, ele percebeu que o atraso gera 2% de juros simples ao dia. Qual o valor que Francinaldo pagou?|5|5|JUROS*CAPITAL*MONTANTE*DESCONTO*AMORTIZAÇÃO|\n" +
                "false|Poupança|Poupança é um tipo de aplicação que o banco oferece aos clientes e o dinheiro aplicado não tem a finalidade de financiamento das atividades do banco.|false|Debênture|São títulos emitidos por empresas não financeira para financiar algum projeto.|true|Certificado de Depósito Bancário (CDB)|Os CDB’s são títulos emitidos pelos bancos para financiar suas atividades de crédito.|false|Ações|É a menor parte de uma empresa, ou seja, são “pedaços” de uma organização que são negociados na bolsa e os acionistas entram no capital social da empresa.|false|Título Público|São títulos emitidos pelo governo como instrumento para seu próprio financiamento e como instrumento de política monetária.|Não é poupança.|fácil|Título que os bancos emitem para se capitalizar, ou seja, conseguir dinheiro para financiar suas atividades de crédito. Tal conceito se refere a:|5|10|INVESTIMENTOS|\n" +
                "false|É preciso refletir antes de tomar crédito e utilizar de forma indiscriminada.|É preciso refletir antes de tomar crédito e utilizar de forma discriminada.|false|O cartão de crédito sempre é a melhor alternativa para realizar compras.|O cartão de crédito nem sempre é a melhor alternativa para realizar compras. As vezes conseguimos um desconto quando fazendo o pagamento à vista.|true|Devemos estar conscientes de que, ao tomar crédito, podemos limitar o consumo futuro.|É preciso lembrar que a tomada de crédito nada mais é do que uma antecipação de uma realização futura, desse modo seu consumo futuro pode estar comprometido caso você utilize essa ferramenta de forma descontrolada.|false|Devo adquirir um produto sempre que a prestação couber no bolso.|Antes de comprar qualquer produto você deve levar em consideração se aquilo é realmente necessário e sempre fazer o custo de oportunidade.|false|Não preciso acompanhar os gastos com o cartão porque há um prazo para pagar.|É preciso acompanhar e controlar todos os gastos com o cartão de crédito para não cair no efeito bola de neve.|Antecipação de uma realização futura|fácil|O uso descontrolado do crédito pode levar ao endividamento e comprometer sua finança pessoal gerando uma série de malefícios. Marque a alternativa que melhor demonstra como evitar esse problema.|5|5|PLANEJAMENTO FINANCEIRO*ORÇAMENTO PESSOAL E FAMILIAR|\n" +
                "false|Juros é o valor que pagamos por usar um dinheiro que é nosso.|Juros é o valor que pagamos por usar um dinheiro que não é nosso.|false|Montante é o valor que foi emprestado.|Montante é o valor que foi emprestado mais os juros que incidiu sobre o valor.|false|A taxa de juros é o valor, em porcentagem, que será aplicado sobre o montante para o cálculo dos juros.|A taxa de juros é o valor, em porcentagem, que será aplicado sobre o capital inicial para o cálculo dos juros.|false|Os juros independem do período de tempo.|O cálculo do juro na sua formulação leva em conta o período de tempo para se adequar as situações.|true|O capital é o valor do montante menos os juros.|O capital é o valor do montante menos os juros|Capital e montante|fácil|Os juros são a base da geração de renda dentro do sistema econômico mundial. Baseado em seus conhecimentos, assinale a alternativa correta.|5|5|JUROS*CAPITAL*MONTANTE*DESCONTO*AMORTIZAÇÃO|\n" +
                "false|R$ 367,20|R$340*0.08 (8%) = R$27,20 de juros ao mês / 3 meses * R$27,20 = R$81,60 / R$340,00 + R$81,60 = R$421,60|true|R$ 421,60|R$340*0.08 (8%) = R$27,20 de juros ao mês / 3 meses * R$27,20 = R$81,60 / R$340,00 + R$81,60 = R$421,60|false|R$ 81,20|R$340*0.08 (8%) = R$27,20 de juros ao mês / 3 meses * R$27,20 = R$81,60 / R$340,00 + R$81,60 = R$421,60|false|R$ 428,30|R$340*0.08 (8%) = R$27,20 de juros ao mês / 3 meses * R$27,20 = R$81,60 / R$340,00 + R$81,60 = R$421,60|false|R$ 394,40|R$340*0.08 (8%) = R$27,20 de juros ao mês / 3 meses * R$27,20 = R$81,60 / R$340,00 + R$81,60 = R$421,60|Valor total é composto pelo capital inicial mais os juros do período.|fácil|Otávio emprestou R$340,00 reais a 8% de juros simples ao mês para Flávio. Flávio pagou a Otávio ao final de três meses. Qual foi o valor pago por Flávio?|5|5|JUROS*CAPITAL*MONTANTE*DESCONTO*AMORTIZAÇÃO|\n" +
                "true|O cheque pré-datado é um acordo informal entre consumidor e fornecedor.|O cheque pré-datado é um acordo informal entre consumidor e fornecedor.|false|O cheque especial é o limite disponível na sua conta corrente.|O cheque especial é o limite que o banco oferece além do seu saldo na conta.|false|O cartão de débito permite que você pague no período após a compra.|O cartão de débito desconta o valor da sua conta corrente no mesmo instante da compra.|false|O cartão de crédito permite que o valor da compra seja descontado da sua conta.|O cartão de crédito permite que o valor da compra seja pago posteriormente ao ato da compra.|false|A transferência entre contas correntes é o meio de pagamento mais demorado.|A transferência entre contas correntes não é o meio de pagamento mais demorado. É um dos mais rápidos.|Acorde entre as partes envolvidas em uma transação de compra e venda.|fácil|Marque a alternativa correta em relação a forma de pagamento.|5|5|CARTÃO DE CRÉDITO*CONCEITOS DE EDUCAÇÃO FINANCEIRA|\n" +
                "true|O empréstimo só deve ser tomado após uma análise da capacidade de pagamento.|O empréstimo só deve ser tomado após uma análise criteriosa em relação a capacidade de pagamento, a capacidade em honrar o compromisso.|false|Não é preciso avaliar a necessidade de se tomar um empréstimo.|É preciso avaliar a necessidade da tomada de um empréstimo para não gerar um endividamento.|false|A tomada de um empréstimo não requer atenção na taxa de juros aplicada.|A taxa de juros é algo primordial para ser observada pelo tomador do empréstimo|false|O empréstimo é a melhor saída para conseguir comprar tudo que você quer.|O empréstimo não é a melhor saída para comprar tudo o que você. Isso gera um descontrole financeira com grandes malefícios.|false|As alternativas 3 e 4 estão corretas.|A única alternativa correta é a número 1. A 3 está errada porque a taxa de juros é algo primordial para ser observada pelo tomador do empréstimo e a 4 está errada porque O empréstimo não é a melhor saída para comprar tudo o que você. Isso gera um descontrole financeira com grandes malefícios.|Análise do seu orçamento pessoal.|fácil|Entendendo empréstimo bancário como sendo um valor que o banco empresta a alguém, que fica obrigado a devolvê-lo, num prazo estimado acrescido de um certo valor (juros). Marque a opção correta.|5|5|GASTOS PESSOAIS*ORÇAMENTO PESSOAL E FAMILIAR|\n" +
                "false|1000 dias|Ex: R$100,00 aplicado a taxa de 1% ao mês rende R$1 real por mês. Para dobrar o valor vão ser necessário 100 meses, como cada mês tem 30 dias, fica 30 dias vezes 100 que resulta em 3000 dias.|false|2000 dias|Ex: R$100,00 aplicado a taxa de 1% ao mês rende R$1 real por mês. Para dobrar o valor vão ser necessário 100 meses, como cada mês tem 30 dias, fica 30 dias vezes 100 que resulta em 3000 dias.|true|3000 dias|Ex: R$100,00 aplicado a taxa de 1% ao mês rende R$1 real por mês. Para dobrar o valor vão ser necessário 100 meses, como cada mês tem 30 dias, fica 30 dias vezes 100 que resulta em 3000 dias.|false|4000 dias|Ex: R$100,00 aplicado a taxa de 1% ao mês rende R$1 real por mês. Para dobrar o valor vão ser necessário 100 meses, como cada mês tem 30 dias, fica 30 dias vezes 100 que resulta em 3000 dias.|false|5000 dias|Ex: R$100,00 aplicado a taxa de 1% ao mês rende R$1 real por mês. Para dobrar o valor vão ser necessário 100 meses, como cada mês tem 30 dias, fica 30 dias vezes 100 que resulta em 3000 dias.|Utilize um valor para a medada. (Ex: R$100,00)|fácil|Marcela resolveu aplicar sua mesada no banco à taxa de 1% ao mês. Sabendo-se que esse valor foi aplicado a juros simples, em quanto tempo (em dias) dobra-se o valor da mesada?|5|10|INVESTIMENTO*VALOR DO DINHEIRO NO TEMPO|\n" +
                "false|Taxa de Juros|A taxa de juros é a remuneração do capital.|false|Taxa de Depreciação|A taxa de depreciação é referente ao capital que é transferido da máquina para o produto.|false|Taxa SELIC|A taxa SELIC é a taxa básica de juros da economia e interfere diretamente na oferta do crédito.|true|Taxa de Câmbio|A taxa de câmbio é o que define de forma indireta o preço de uma unidade de moeda em unidades (ou frações) de outra moeda.|false|Taxa de Inflação|A taxa de inflação refere-se a o aumento contínuo de generalizado dos preços dos produtos.|Casa de câmbio|fácil|A taxa que define de forma indireta o preço de uma unidade de moeda em unidades (ou frações) de outra moeda é conhecida como:|5|5|MOEDAS|\n" +
                "false|Banco Central do Brasil (BACEN)|O Banco Central é a entidade responsável pela política monetária e pela regulação dos bancos no Brasil.|true|Comissão de Valores Mobiliários (CVM)|A Comissão de Valores Mobiliários é o órgão responsável pela regulação do mercado de capitais brasileiro.|false|Ministério da Economia (ME)|O ministério da economia é responsável por assuntos ligados a economia brasileira como um todo.|false|Receita Federal do Brasil (RFB)|A Receita Federal do Brasil é a entidade responsável pelas questões fiscais brasileira.|false|Conselho Monetário Nacional (CMN)|Conselho Monetário Nacional é uma subdivisão dentro do Banco Central responsável por questões relacionada mais especificamente a política monetária no Brasil.|Não é muito comum ouvir falar desse órgão.|fácil|Órgão responsável pela regulação do mercado de capitais no Brasil:|5|5|CONCEITOS DE EDUCAÇÃO FINANCEIRA|\n" +
                "false|O retorno de uma aplicação segura é alto e de uma aplicação arriscada é baixa.|Em geral as aplicações financeiras mais seguras tendem a oferecer uma taxa de retorno mais baixa em comparação as aplicações financeiras mais arriscadas.|true|O retorno de uma aplicação segura é baixo e de uma aplicação arriscada alta.|Em geral as aplicações financeiras mais seguras tendem a oferecer uma taxa de retorno mais baixa em comparação as aplicações financeiras mais arriscadas.|false|O retorno de uma aplicação segura e de uma aplicação arriscada são iguais.|Em geral as aplicações financeiras mais seguras tendem a oferecer uma taxa de retorno mais baixa em comparação as aplicações financeiras mais arriscadas.|false|A poupança é uma aplicação segura, pois possui uma taxa de retorno alta.|A caderneta de poupança é um investimento seguro, por isso possui uma baixa taxa de retorno.|false|A poupança é uma aplicação arriscada, pois possui uma taxa de retorno alta.|A caderneta de poupança é um investimento seguro, por isso possui uma baixa taxa de retorno.|Quando maior o risco, em geral, maior o retorno.|fácil|Em relação ao risco e à taxa de retorno de um investimento, podemos afirmar que:|5|5|INVESTIMENTO|\n" +
                "false|Ato de gastar sem pensar no futuro|O ato de gastar sem pensar no futuro é uma das ações que é combatida pelo planejamento financeiro.|false|Ação de não pensar antes de gastar|Ação de pensar antes de gastar é que faz parte do planejamento financeiro.|true|Um trabalho onde se estabelece objetivos, prazos e os meios para se realizar.|O planejamento financeiro consiste no estabelecimento de objetivos e metas a serem alcançadas.|false|Comprar tudo que vemos pela frente, sem pensar.|Comprar tudo que vemos vai de encontro ao princípio do gasto consciente propagado pelo planejamento financeiro.|false|É um desperdício de dinheiro e pode fazer falta no fim do mês.|O planejamento financeiro evita esse desperdício de dinheiro.|Realização de sonhos|fácil|O que é um Planejamento Financeiro? Marque a alternativa correta:|5|5|PLANEJAMENTO FINANCEIRO|\n" +
                "false|A relação entre a oferta e a demanda de dinheiro.|Essa relação se refere a disponibilidade de dinheiro no sistema econômico.|false|A relação entre dinheiro gasto e dinheiro recebido.|Essa relação se refere ao fluxo de caixa.|true|A relação entre um real a ser recebido no futuro e um real hoje.|A relação de percepção do valor do dinheiro hoje e no futuro.|false|A relação entre a taxa de juros declarada e o valor pago.|Esse conceito se refere a taxa efetiva de juros.|false|A relação entre o valor da receita com relação ao lucro.|SEM JUSTIFICATIVA|Relação entre o presente o futuro|fácil|O conceito de valor do dinheiro no tempo pode ser definido como:|5|5|VALOR DO DINHEIRO NO TEMPO");
        final List<Questao> lista=lerQuestao("NovasQuestoes.txt");
        /*firebase.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot dataSnapshot) {
                int contQuestoes=dataSnapshot.child("contQuestoes").getValue(Integer.class);
                int quantQuestoes=dataSnapshot.child("quantQuestoes").getValue(Integer.class);

                for(Questao q:lista){
                    quantQuestoes++;
                    contQuestoes++;
                    firebase.child("contQuestoes").setValue(contQuestoes);
                    firebase.child("quantQuestoes").setValue(quantQuestoes);
                    firebase.child("Questoes").setValue(q);
                    firebase.child("idQuestao").child("q"+quantQuestoes).setValue(contQuestoes);

                }

            }

            @Override
            public void onCancelled(@NonNull DatabaseError databaseError) {

            }
        });*/

    }
    public void gravarArquivo(String nomeArquivo, String texto){
        try {
            OutputStreamWriter buff=new OutputStreamWriter(new FileOutputStream("/data/data/com.example.myapplication/files/"+nomeArquivo),"UTF-8");
            buff.write(texto);
            buff.close();
        } catch (FileNotFoundException e) {
            System.out.println("1");
            e.printStackTrace();
        } catch (UnsupportedEncodingException e) {
            System.out.println("2");
            e.printStackTrace();
        } catch (IOException e) {
            System.out.println("3");
            e.printStackTrace();
        }
    }

    public String lerArquivo(String nomeArquivo){
        String s="";
        BufferedReader buff;
        try {
            buff= new BufferedReader(new InputStreamReader(new FileInputStream("/data/data/com.example.myapplication/files/"+nomeArquivo),"UTF-8"));
            String linha=buff.readLine();
            while(linha!=null){
                s+=linha+"\n";
                linha=buff.readLine();
            }
            buff.close();
        } catch (UnsupportedEncodingException e) {
            System.out.println("4");
            e.printStackTrace();
        } catch (FileNotFoundException e) {
            System.out.println("5");
            e.printStackTrace();
        } catch (IOException e) {
            System.out.println("6");
            e.printStackTrace();
        }
        return s;
    }
    public List<Questao> lerQuestao(String nomeArquivo){
        String arquivo = lerArquivo(nomeArquivo);
        Scanner sc=new Scanner(arquivo).useDelimiter("\\|");
        List<Questao> questoes=new ArrayList<Questao>();
        while(sc.hasNext()) {
            String teste=sc.next();
            if(teste.equals("")){
                System.out.println("Ficou duas aspas");
            }
            if(teste==null){
                System.out.println("Ficou nulo");
            }
            System.out.println("asd "+teste);
            boolean b=Boolean.parseBoolean(teste);
            Alternativa a1 = new Alternativa(b, sc.next(), sc.next());
            Alternativa a2 = new Alternativa(Boolean.parseBoolean(sc.next()), sc.next(), sc.next());
            Alternativa a3 = new Alternativa(Boolean.parseBoolean(sc.next()), sc.next(), sc.next());
            Alternativa a4 = new Alternativa(Boolean.parseBoolean(sc.next()), sc.next(), sc.next());
            Alternativa a5 = new Alternativa(Boolean.parseBoolean(sc.next()), sc.next(), sc.next());
            String dica = sc.next();
            String dificuldade = sc.next();
            String enunciado = sc.next();
            int nivel = Integer.parseInt(sc.next());
            int valor = Integer.parseInt(sc.next());
            String tema = sc.next();
            Questao questao = new Questao(a1, a2, a3, a4, a5, dica, dificuldade, enunciado, nivel, valor, tema);
            questoes.add(questao);
            System.out.println(questoes.size());


        }
        sc.close();
        return questoes;
    }


}

